<h1>Users</h1>

<br />

<p>
    <a class="btn btn-success" href="<?php echo $this->url('sonuser-admin/default',array('action'=>'new')); ?>"><i class="fa fa-plus"></i> Novo</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
    <tr>
    
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getNome(); ?></td>
        <td><?php echo $entity->getEmail(); ?></td>
        <td>
            <a class="btn btn-warning btn-xs" href="<?php echo $this->url('sonuser-admin/default',
                    array('controller'=>'users','action'=>'edit','id'=>$entity->getId()));?>"><i class="fa fa-pencil"></i> Editar</a>
            
            <a class="btn btn-danger btn-xs" href="<?php echo $this->url('sonuser-admin/default',
                    array('controller'=>'users','action'=>'delete','id'=>$entity->getId()));?>"><i class="fa fa-trash"></i> Delete</a>
            
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>